[tools]
buf = "latest"
dbmate = "latest"
dive = "latest"
eza = "latest"
go = "latest"
kubectx = "latest"
lazygit = "latest"
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"
sops = "latest"
stern = "latest"

[settings]
python.compile = false
python.uv_venv_auto = "create|source"
trusted_config_paths = ["~/dotfiles/mise/"]
idiomatic_version_file_enable_tools = ["node", "python", "ruby"]
